# Generated by Django 6.0.4 on 2026-09-18 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml65app', '0006_patientprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
