# Generated by Django 6.0.4 on 2026-09-19 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml65app', '0007_alter_patientprofile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='mobile',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('PATIENT', 'Patient'), ('HOSPITAL', 'Hospital'), ('DOCTOR', 'Doctor'), ('HEALTH_WORKER', 'Health Worker'), ('MEDICAL_SHOP', 'Medical Shop'), ('BLOOD_BANK', 'Blood Bank')], max_length=20),
        ),
    ]
