# Generated by Django 6.1.1 on 2026-09-20 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml65app', '0008_userprofile_mobile_alter_userprofile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprediction',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='predictions', to='ml65app.patientprofile'),
        ),
    ]
